let mock = [
	{
		id: 1,
		title: 'Kind of Blue',
		artist: 'Miles Davis',
		year: '1959',
		genre: 'Jazz',
		image: 'blue.jpeg',
	},
	{
		id: 2,
		title: 'Birth of the Cool',
		artist: 'Miles Davis',
		year: '1957',
		genre: 'Jazz',
		image: 'cool.jpeg',
	},
	{
		id: 3,
		title: 'Miles Ahead',
		artist: 'Miles Davis',
		year: '1957',
		genre: 'Jazz',
		image: 'miles-ahead.jpeg',
	},
	{
		id: 4,
		title: 'Milestones',
		artist: 'Miles Davis',
		year: '1958',
		genre: 'Jazz',
		image: 'milestones.jpeg',
	},
	{
		id: 5,
		title: 'Blue Train',
		artist: 'John Coltrane',
		year: '1958',
		genre: 'Jazz',
		image: 'train.jpeg',
	},
	{
		id: 6,
		title: 'A Love Supreme',
		artist: 'John Coltrane',
		year: '1965',
		genre: 'Jazz',
		image: 'supreme.jpg',
	},
	{
		id: 7,
		title: "Moanin'",
		artist: 'Art Blakey and the Jazz Messengers',
		year: '1959',
		genre: 'Jazz',
		image: 'moanin.jpeg',
	},
	{
		id: 8,
		title: 'A Night in Tunisia',
		artist: 'Art Blakey and the Jazz Messengers',
		year: '1961',
		genre: 'Jazz',
		image: 'tunisia.jpeg',
	},
	{
		id: 9,
		title: 'Heavy Weather',
		artist: 'Weather Report',
		year: '1977',
		genre: 'Fusion',
		image: 'heavy-weather.jpeg',
	},
	{
		id: 10,
		title: 'Mysterious Traveller',
		artist: 'Weather Report',
		year: '1974',
		genre: 'Fusion',
		image: 'traveller.jpeg',
	},
	{
		id: 11,
		title: 'Back to Oakland',
		artist: 'Tower of Power',
		year: '1974',
		genre: 'Funk',
		image: 'oakland.jpeg',
	},
	{
		id: 12,
		title: 'Warna',
		artist: 'Joey Alexander',
		year: '2020',
		genre: 'Jazz',
		image: 'warna.png',
	},
	{
		id: 13,
		title: 'A Farewell to Kings',
		artist: 'Rush',
		year: '1977',
		genre: 'Rock',
		image: 'kings.jpeg',
	},
	{
		id: 14,
		title: 'Hemispheres',
		artist: 'Rush',
		year: '1978',
		genre: 'Rock',
		image: 'hemispheres.jpeg',
	},
	{
		id: 15,
		title: 'Permanent Waves',
		artist: 'Rush',
		year: '1980',
		genre: 'Rock',
		image: 'waves.jpeg',
	},
	{
		id: 16,
		title: 'Moving Pictures',
		artist: 'Rush',
		year: '1981',
		genre: 'Rock',
		image: 'moving-pictures.jpeg',
	},
	{
		id: 17,
		title: 'Signals',
		artist: 'Rush',
		year: '1982',
		genre: 'Rock',
		image: 'signals.jpeg',
	},
	{
		id: 18,
		title: 'Grace Under Pressure',
		artist: 'Rush',
		year: '1984',
		genre: 'Rock',
		image: 'grace.jpeg',
	},
	{
		id: 19,
		title: 'Clockwork Angels',
		artist: 'Rush',
		year: '2012',
		genre: 'Rock',
		image: 'clockwork.png',
	},
	{
		id: 20,
		title: 'The College Dropout',
		artist: 'Kanye West',
		year: '2004',
		genre: 'Hip Hop',
		image: 'dropout.jpeg',
	},
	{
		id: 21,
		title: 'Late Registration',
		artist: 'Kanye West',
		year: '2005',
		genre: 'Hip Hop',
		image: 'registration.jpeg',
	},
	{
		id: 22,
		title: 'Graduation',
		artist: 'Kanye West',
		year: '2007',
		genre: 'Hip Hop',
		image: 'graduation.jpeg',
	},
	{
		id: 23,
		title: '808s & Heartbreak',
		artist: 'Kanye West',
		year: '2008',
		genre: 'Hip Hop',
		image: '808.png',
	},
	{
		id: 24,
		title: 'The Life of Pablo',
		artist: 'Kanye West',
		year: '2016',
		genre: 'Hip Hop',
		image: 'pablo.jpeg',
	},
	{
		id: 25,
		title: 'Ye',
		artist: 'Kanye West',
		year: '2018',
		genre: 'Hip Hop',
		image: 'ye.jpeg',
	},
	{
		id: 26,
		title: 'Jesus is King',
		artist: 'Kanye West',
		year: '2019',
		genre: 'Gospel',
		image: 'jesus-king.png',
	},
	{
		id: 27,
		title: 'Donda',
		artist: 'Kanye West',
		year: '2021',
		genre: 'Hip Hop',
		image: 'donda.png',
	},
];

export default mock;
